export const data = [{
    id: 1,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 2,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
}, {
    id: 3,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
}, {
    id: 4,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
}, {
    id: 5,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
}, {
    id: 6,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 7,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 8,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 9,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 10,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 11,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "空军基地就",
    qita2: "空军基地就",
    qita3: "空军基地就",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 12,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "++++++++++++",
    qita2: "++++++++++++",
    qita3: "++++++++++++",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 13,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "++++++++++++",
    qita2: "++++++++++++",
    qita3: "++++++++++++",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
},
{
    id: 14,
    name: 222,
    age: 30,
    lang: 666,
    qita1: "++++++++++++",
    qita2: "++++++++++++",
    qita3: "++++++++++++",
    qita4: "空军基地就",
    qita5: "空军基地就",
    qita6: "空军基地就",
    qita7: "空军基地就",
    qita8: "空军基地就",
    qita9: "空军基地就",
}]

export const columns = [{
    prop: "name",
    label: "防守打法111",
    show: false,
    width: 300,
},
{
    prop: "age",
    label: "年龄",
    show: true,
    width: 300,
},
{
    prop: "lang",
    label: "升高",
    width: 300,
},
{
    prop: "qita1",
    label: "其他1发撒地方撒发水电费水电费水电费",
    width: 300,
},
{
    prop: "qita2",
    label: "其他2",
    width: 300,
},
{
    prop: "qita3",
    label: "其他3",
    'min-width': 300,
},
{
    prop: "qita4",
    label: "其他4",
    width: 300,
},
{
    prop: "qita5",
    label: "其他5",
    width: 300,
},
{
    prop: "qita6",
    label: "其他6",
    width: 300,
},
{
    prop: "qita7",
    label: "其他7",
    width: 300,
},
{
    prop: "qita8",
    label: "其他8",
    width: 300,
},
{
    prop: "qita9",
    label: "其他9",
    width: 300,
    fixed: 'right'
}]

export const columns2 = [{
    prop: "name",
    label: "防守打法222",
    show: false,
    width: 300,
},
{
    prop: "age",
    label: "年龄",
    show: true,
    width: 300,
},
{
    prop: "lang",
    label: "升高",
    width: 300,
},
{
    prop: "qita1",
    label: "其他1发撒地方撒发水电费水电费水电费",
    width: 300,
},
{
    prop: "qita2",
    label: "其他2",
    width: 300,
},
{
    prop: "qita3",
    label: "其他3",
    'min-width': 300,
},
{
    prop: "qita4",
    label: "其他4",
    width: 300,
},
{
    prop: "qita5",
    label: "其他5",
    width: 300,
},
{
    prop: "qita6",
    label: "其他6",
    width: 300,
},
{
    prop: "qita7",
    label: "其他7",
    width: 300,
},
{
    prop: "qita8",
    label: "其他8",
    width: 300,
},
{
    prop: "qita9",
    label: "其他9",
    width: 300,
    fixed: 'right'
}]

export const columns3 = [{
    prop: "name",
    label: "防守打法333",
    show: false,
    width: 300,
},
{
    prop: "age",
    label: "年龄",
    show: true,
    width: 300,
},
{
    prop: "lang",
    label: "升高",
    width: 300,
},
{
    prop: "qita1",
    label: "其他1发撒地方撒发水电费水电费水电费",
    width: 300,
},
{
    prop: "qita2",
    label: "其他2",
    width: 300,
},
{
    prop: "qita3",
    label: "其他3",
    'min-width': 300,
},
{
    prop: "qita4",
    label: "其他4",
    width: 300,
},
{
    prop: "qita5",
    label: "其他5",
    width: 300,
},
{
    prop: "qita6",
    label: "其他6",
    width: 300,
},
{
    prop: "qita7",
    label: "其他7",
    width: 300,
},
{
    prop: "qita8",
    label: "其他8",
    width: 300,
},
{
    prop: "qita9",
    label: "其他9",
    width: 300,
    fixed: 'right'
}]

export const tabl = [
    {
        id: '1',
        name: "第一"
    },
    {
        id: '2',
        name: "第一"
    },
    {
        id: '3',
        name: "第一"
    },
    {
        id: '4',
        name: "第一"
    },
]